### ISSUE TITLE
Week 9 Day 2 - Who are you?  - 

### ISSUE THREAD

**Issue by mdewey** [katerigney/assignments#33]
# Who are you? 

Today we talked about authentication. Tonight, follow along with this tutorial to learn and understand token based authenication with AngularJS 

# Explorer

- [ ] Follow Part 1 and 2 of this tutorial http://bitoftech.net/2014/06/01/token-based-authentication-asp-net-web-api-2-owin-asp-net-identity/
- [ ] Code along with it and submit that as your solution

PROTIP: 
- Do not move onto the next step until the current step works. 
- Ask Plenty of questions. There will be words that are unfamiliar to you

# Adventure

- [ ] Round off your group project from last night. 
- [ ] Auth Authentication to your news site. This can be done with your groups or not, your choice.

# Epic
- [ ] Add OAuth to your site news site and allow the users to log in with Google

**Comment by katerigney** [comment]
Part 1 working for sure: https://github.com/katerigney/AngularJSAuthentication

Personal stuff came up. Build out files from tutorial but really need to go in and look and the files from the github to look at what is happening on the angular side

**Comment by katerigney** [comment]
During warm up Chris explained about the project wanting to talk to the index on the API side. If I move the file over there, something actually displays. But not well. And I'm still confused bc the tutorial put it in the web side.

**Comment by mdewey** [comment]
![Awesome Work!](https://media0.giphy.com/media/cdDwOUeF4XyE0/200w_d.gif)
